import { Exercise } from './types'

export const EXERCISES: Exercise[] = [
  // ── CHEST ──────────────────────────────────────────────────────────────────
  {
    id: 'push_up',
    name: 'Push-Up',
    muscle_groups: ['chest', 'triceps', 'shoulders'],
    equipment: ['bodyweight'],
    gif_url: 'https://fitnessprogramer.com/wp-content/uploads/2021/02/Push-Up.gif',
    youtube_url: 'https://youtube.com/shorts/pkPp_K_zE2E',
    default_sets: 3, default_reps: '10-15',
    instructions: 'Keep core tight, lower chest to floor, push back up.',
    difficulty: 'beginner',
  },
  {
    id: 'wide_push_up',
    name: 'Wide Push-Up',
    muscle_groups: ['chest', 'triceps'],
    equipment: ['bodyweight'],
    gif_url: 'https://fitnessprogramer.com/wp-content/uploads/2021/02/Wide-Push-Up.gif',
    youtube_url: 'https://youtube.com/shorts/0pkjOk0EiAk',
    default_sets: 3, default_reps: '10-12',
    instructions: 'Hands wider than shoulder width; emphasizes outer chest.',
    difficulty: 'beginner',
  },
  {
    id: 'diamond_push_up',
    name: 'Diamond Push-Up',
    muscle_groups: ['chest', 'triceps'],
    equipment: ['bodyweight'],
    gif_url: 'https://fitnessprogramer.com/wp-content/uploads/2021/04/Diamond-Push-Up.gif',
    youtube_url: 'https://youtube.com/shorts/J0DnG1_S92I',
    default_sets: 3, default_reps: '8-12',
    instructions: 'Thumbs and index fingers touching; hits inner chest and triceps.',
    difficulty: 'intermediate',
  },
  {
    id: 'incline_push_up',
    name: 'Incline Push-Up',
    muscle_groups: ['chest', 'triceps'],
    equipment: ['bodyweight', 'bench'],
    gif_url: 'https://fitnessprogramer.com/wp-content/uploads/2021/05/Incline-Push-Up.gif',
    youtube_url: 'https://youtube.com/shorts/cfns5pRUq9s',
    default_sets: 3, default_reps: '12-15',
    instructions: 'Hands on bench; targets lower chest.',
    difficulty: 'beginner',
  },
  {
    id: 'decline_push_up',
    name: 'Decline Push-Up',
    muscle_groups: ['chest', 'shoulders'],
    equipment: ['bodyweight', 'bench'],
    gif_url: 'https://fitnessprogramer.com/wp-content/uploads/2021/05/Decline-Push-Up.gif',
    youtube_url: 'https://youtube.com/shorts/SKPab2YC8BE',
    default_sets: 3, default_reps: '8-12',
    instructions: 'Feet elevated on bench; emphasizes upper chest.',
    difficulty: 'intermediate',
  },
  {
    id: 'db_chest_press',
    name: 'Dumbbell Chest Press',
    muscle_groups: ['chest', 'triceps', 'shoulders'],
    equipment: ['dumbbells', 'bench'],
    gif_url: 'https://fitnessprogramer.com/wp-content/uploads/2021/02/Dumbbell-Bench-Press.gif',
    youtube_url: 'https://youtube.com/shorts/VmB1G1K7v94',
    default_sets: 4, default_reps: '8-12',
    instructions: 'Lie on bench, press dumbbells from chest to full extension.',
    difficulty: 'intermediate',
  },
  {
    id: 'db_chest_fly',
    name: 'Dumbbell Chest Fly',
    muscle_groups: ['chest'],
    equipment: ['dumbbells', 'bench'],
    gif_url: 'https://fitnessprogramer.com/wp-content/uploads/2021/02/Dumbbell-Fly.gif',
    youtube_url: 'https://youtube.com/shorts/eozdVDA78K0',
    default_sets: 3, default_reps: '10-15',
    instructions: 'Wide arc motion; slight bend in elbows throughout.',
    difficulty: 'intermediate',
  },

  // ── BACK ───────────────────────────────────────────────────────────────────
  {
    id: 'pull_up',
    name: 'Pull-Up',
    muscle_groups: ['back', 'biceps'],
    equipment: ['pull_up_bar'],
    gif_url: 'https://fitnessprogramer.com/wp-content/uploads/2021/02/Pull-up.gif',
    youtube_url: 'https://youtube.com/shorts/eGo4IYlbE5g',
    default_sets: 3, default_reps: '5-10',
    instructions: 'Overhand grip; pull until chin clears bar.',
    difficulty: 'intermediate',
  },
  {
    id: 'chin_up',
    name: 'Chin-Up',
    muscle_groups: ['back', 'biceps'],
    equipment: ['pull_up_bar'],
    gif_url: 'https://fitnessprogramer.com/wp-content/uploads/2021/02/Chin-Up.gif',
    youtube_url: 'https://youtube.com/shorts/b-ztMQpj8yc',
    default_sets: 3, default_reps: '5-10',
    instructions: 'Underhand grip; more bicep activation than pull-up.',
    difficulty: 'intermediate',
  },
  {
    id: 'inverted_row',
    name: 'Inverted Row',
    muscle_groups: ['back', 'biceps'],
    equipment: ['pull_up_bar'],
    gif_url: 'https://fitnessprogramer.com/wp-content/uploads/2021/06/Australian-Pull-Up.gif',
    youtube_url: 'https://youtube.com/shorts/B4bHMFCmRTI',
    default_sets: 3, default_reps: '10-15',
    instructions: 'Body below bar at 45°; pull chest to bar.',
    difficulty: 'beginner',
  },
  {
    id: 'db_bent_over_row',
    name: 'Dumbbell Bent-Over Row',
    muscle_groups: ['back', 'biceps'],
    equipment: ['dumbbells'],
    gif_url: 'https://fitnessprogramer.com/wp-content/uploads/2021/02/Bent-Over-Dumbbell-Row.gif',
    youtube_url: 'https://youtube.com/shorts/6TSP1TRMUzs',
    default_sets: 4, default_reps: '8-12',
    instructions: 'Hinge at hips 45°; pull elbows past torso.',
    difficulty: 'intermediate',
  },
  {
    id: 'db_single_arm_row',
    name: 'Single-Arm Dumbbell Row',
    muscle_groups: ['back', 'biceps'],
    equipment: ['dumbbells', 'bench'],
    gif_url: 'https://fitnessprogramer.com/wp-content/uploads/2021/02/One-Arm-Dumbbell-Row.gif',
    youtube_url: 'https://youtube.com/shorts/pYcpY20QaE8',
    default_sets: 3, default_reps: '10-12',
    instructions: 'Knee and hand on bench; pull dumbbell to hip.',
    difficulty: 'beginner',
  },
  {
    id: 'superman',
    name: 'Superman',
    muscle_groups: ['back'],
    equipment: ['bodyweight'],
    gif_url: 'https://fitnessprogramer.com/wp-content/uploads/2021/02/Superman.gif',
    youtube_url: 'https://youtube.com/shorts/z6PJMT2y8GQ',
    default_sets: 3, default_reps: '12-15',
    instructions: 'Lie prone; lift arms and legs simultaneously.',
    difficulty: 'beginner',
  },
  {
    id: 'resistance_band_row',
    name: 'Resistance Band Row',
    muscle_groups: ['back', 'biceps'],
    equipment: ['resistance_bands'],
    gif_url: 'https://fitnessprogramer.com/wp-content/uploads/2021/06/Resistance-Band-Seated-Row.gif',
    youtube_url: 'https://youtube.com/shorts/R3lkNq3AAXI',
    default_sets: 3, default_reps: '12-15',
    instructions: 'Anchor band at chest height; pull elbows back.',
    difficulty: 'beginner',
  },

  // ── SHOULDERS ──────────────────────────────────────────────────────────────
  {
    id: 'pike_push_up',
    name: 'Pike Push-Up',
    muscle_groups: ['shoulders', 'triceps'],
    equipment: ['bodyweight'],
    gif_url: 'https://fitnessprogramer.com/wp-content/uploads/2021/06/Pike-Push-Up.gif',
    youtube_url: 'https://youtube.com/shorts/sposDXWEB0A',
    default_sets: 3, default_reps: '8-12',
    instructions: 'Hips high in V shape; lower head toward floor.',
    difficulty: 'intermediate',
  },
  {
    id: 'db_shoulder_press',
    name: 'Dumbbell Shoulder Press',
    muscle_groups: ['shoulders', 'triceps'],
    equipment: ['dumbbells'],
    gif_url: 'https://fitnessprogramer.com/wp-content/uploads/2021/02/Dumbbell-Shoulder-Press.gif',
    youtube_url: 'https://youtube.com/shorts/qEwKCR5JCog',
    default_sets: 4, default_reps: '8-12',
    instructions: 'Press from ear level to full extension overhead.',
    difficulty: 'intermediate',
  },
  {
    id: 'db_lateral_raise',
    name: 'Dumbbell Lateral Raise',
    muscle_groups: ['shoulders'],
    equipment: ['dumbbells'],
    gif_url: 'https://fitnessprogramer.com/wp-content/uploads/2021/02/Dumbbell-Lateral-Raise.gif',
    youtube_url: 'https://youtube.com/shorts/3VcKaXpzqRo',
    default_sets: 3, default_reps: '12-15',
    instructions: 'Slight elbow bend; raise to shoulder height.',
    difficulty: 'beginner',
  },
  {
    id: 'db_front_raise',
    name: 'Dumbbell Front Raise',
    muscle_groups: ['shoulders'],
    equipment: ['dumbbells'],
    gif_url: 'https://fitnessprogramer.com/wp-content/uploads/2021/02/Dumbbell-Front-Raise.gif',
    youtube_url: 'https://youtube.com/shorts/sOoBHDVTqgg',
    default_sets: 3, default_reps: '12-15',
    instructions: 'Raise dumbbells to shoulder height.',
    difficulty: 'beginner',
  },
  {
    id: 'band_face_pull',
    name: 'Band Face Pull',
    muscle_groups: ['shoulders', 'back'],
    equipment: ['resistance_bands'],
    gif_url: 'https://fitnessprogramer.com/wp-content/uploads/2021/06/Face-Pull-With-Resistance-Band.gif',
    youtube_url: 'https://youtube.com/shorts/eIq5CB9JfKE',
    default_sets: 3, default_reps: '15-20',
    instructions: 'Anchor at face height; pull toward face, flare elbows.',
    difficulty: 'beginner',
  },

  // ── BICEPS ─────────────────────────────────────────────────────────────────
  {
    id: 'db_curl',
    name: 'Dumbbell Bicep Curl',
    muscle_groups: ['biceps'],
    equipment: ['dumbbells'],
    gif_url: 'https://fitnessprogramer.com/wp-content/uploads/2021/02/Dumbbell-Curl.gif',
    youtube_url: 'https://youtube.com/shorts/ykJmrZ5v0Oo',
    default_sets: 3, default_reps: '10-12',
    instructions: 'Keep elbows pinned at sides; full range of motion.',
    difficulty: 'beginner',
  },
  {
    id: 'hammer_curl',
    name: 'Hammer Curl',
    muscle_groups: ['biceps'],
    equipment: ['dumbbells'],
    gif_url: 'https://fitnessprogramer.com/wp-content/uploads/2021/02/Hammer-Curl.gif',
    youtube_url: 'https://youtube.com/shorts/zC3nLlEvin4',
    default_sets: 3, default_reps: '10-12',
    instructions: 'Neutral (thumbs up) grip; hits brachialis.',
    difficulty: 'beginner',
  },
  {
    id: 'band_curl',
    name: 'Resistance Band Curl',
    muscle_groups: ['biceps'],
    equipment: ['resistance_bands'],
    gif_url: 'https://fitnessprogramer.com/wp-content/uploads/2021/06/Resistance-Band-Bicep-Curl.gif',
    youtube_url: 'https://youtube.com/shorts/JkVQRDJPDcI',
    default_sets: 3, default_reps: '12-15',
    instructions: 'Stand on band; curl with full contraction.',
    difficulty: 'beginner',
  },
  {
    id: 'concentration_curl',
    name: 'Concentration Curl',
    muscle_groups: ['biceps'],
    equipment: ['dumbbells'],
    gif_url: 'https://fitnessprogramer.com/wp-content/uploads/2021/02/Concentration-Curl.gif',
    youtube_url: 'https://youtube.com/shorts/0AqaGEaZ8rY',
    default_sets: 3, default_reps: '10-12',
    instructions: 'Sit, elbow on inner thigh; curl for full peak contraction.',
    difficulty: 'beginner',
  },

  // ── TRICEPS ────────────────────────────────────────────────────────────────
  {
    id: 'tricep_dip',
    name: 'Chair Tricep Dip',
    muscle_groups: ['triceps', 'chest'],
    equipment: ['bodyweight', 'bench'],
    gif_url: 'https://fitnessprogramer.com/wp-content/uploads/2021/02/Bench-Dip.gif',
    youtube_url: 'https://youtube.com/shorts/0326dy_-CzM',
    default_sets: 3, default_reps: '10-15',
    instructions: 'Hands on chair edge; lower hips toward floor.',
    difficulty: 'beginner',
  },
  {
    id: 'db_overhead_tricep_ext',
    name: 'DB Overhead Tricep Extension',
    muscle_groups: ['triceps'],
    equipment: ['dumbbells'],
    gif_url: 'https://fitnessprogramer.com/wp-content/uploads/2021/02/Dumbbell-Triceps-Extension.gif',
    youtube_url: 'https://youtube.com/shorts/YbX7Wd8jQ-Q',
    default_sets: 3, default_reps: '10-12',
    instructions: 'Hold dumbbell overhead; lower behind head, extend.',
    difficulty: 'beginner',
  },
  {
    id: 'db_tricep_kickback',
    name: 'Dumbbell Tricep Kickback',
    muscle_groups: ['triceps'],
    equipment: ['dumbbells'],
    gif_url: 'https://fitnessprogramer.com/wp-content/uploads/2021/02/Triceps-Kickback.gif',
    youtube_url: 'https://youtube.com/shorts/6SS6K3lAwZ8',
    default_sets: 3, default_reps: '12-15',
    instructions: 'Hinge forward; extend arm fully back.',
    difficulty: 'beginner',
  },
  {
    id: 'diamond_push_up_tricep',
    name: 'Close-Grip Push-Up',
    muscle_groups: ['triceps', 'chest'],
    equipment: ['bodyweight'],
    gif_url: 'https://fitnessprogramer.com/wp-content/uploads/2022/01/Close-Grip-Push-Up.gif',
    youtube_url: 'https://youtube.com/shorts/U6NuHSUUbzI',
    default_sets: 3, default_reps: '8-12',
    instructions: 'Hands shoulder-width; elbows track close to body.',
    difficulty: 'intermediate',
  },

  // ── LEGS ───────────────────────────────────────────────────────────────────
  {
    id: 'squat',
    name: 'Bodyweight Squat',
    muscle_groups: ['legs', 'glutes'],
    equipment: ['bodyweight'],
    gif_url: 'https://fitnessprogramer.com/wp-content/uploads/2021/02/squat.gif',
    youtube_url: 'https://youtube.com/shorts/aclHkVaku9U',
    default_sets: 3, default_reps: '15-20',
    instructions: 'Feet shoulder width; descend until thighs parallel.',
    difficulty: 'beginner',
  },
  {
    id: 'goblet_squat',
    name: 'Goblet Squat',
    muscle_groups: ['legs', 'glutes'],
    equipment: ['dumbbells'],
    gif_url: 'https://fitnessprogramer.com/wp-content/uploads/2021/04/Goblet-Squat.gif',
    youtube_url: 'https://youtube.com/shorts/MeIiIdhvXT4',
    default_sets: 4, default_reps: '10-15',
    instructions: 'Hold dumbbell at chest; keep torso upright.',
    difficulty: 'beginner',
  },
  {
    id: 'bulgarian_split_squat',
    name: 'Bulgarian Split Squat',
    muscle_groups: ['legs', 'glutes'],
    equipment: ['bodyweight', 'bench'],
    gif_url: 'https://fitnessprogramer.com/wp-content/uploads/2021/04/Bulgarian-Split-Squat.gif',
    youtube_url: 'https://youtube.com/shorts/2C-uNgKwPLE',
    default_sets: 3, default_reps: '8-10',
    instructions: 'Rear foot elevated; lower back knee toward floor.',
    difficulty: 'intermediate',
  },
  {
    id: 'lunge',
    name: 'Walking Lunge',
    muscle_groups: ['legs', 'glutes'],
    equipment: ['bodyweight'],
    gif_url: 'https://fitnessprogramer.com/wp-content/uploads/2021/02/Lunge.gif',
    youtube_url: 'https://youtube.com/shorts/L8fvypPrzzs',
    default_sets: 3, default_reps: '10-12',
    instructions: 'Step forward; lower back knee near floor.',
    difficulty: 'beginner',
  },
  {
    id: 'db_romanian_deadlift',
    name: 'Dumbbell Romanian Deadlift',
    muscle_groups: ['legs', 'glutes', 'back'],
    equipment: ['dumbbells'],
    gif_url: 'https://fitnessprogramer.com/wp-content/uploads/2021/02/Dumbbell-Romanian-Deadlift.gif',
    youtube_url: 'https://youtube.com/shorts/7j-2pitPseU',
    default_sets: 4, default_reps: '8-12',
    instructions: 'Hinge at hips; feel hamstring stretch, drive hips forward.',
    difficulty: 'intermediate',
  },
  {
    id: 'step_up',
    name: 'Step-Up',
    muscle_groups: ['legs', 'glutes'],
    equipment: ['bodyweight', 'bench'],
    gif_url: 'https://fitnessprogramer.com/wp-content/uploads/2021/06/Step-Up.gif',
    youtube_url: 'https://youtube.com/shorts/dQqApCGd5Ss',
    default_sets: 3, default_reps: '10-12',
    instructions: 'Step fully onto platform; drive through heel.',
    difficulty: 'beginner',
  },
  {
    id: 'jump_squat',
    name: 'Jump Squat',
    muscle_groups: ['legs', 'glutes'],
    equipment: ['bodyweight'],
    gif_url: 'https://fitnessprogramer.com/wp-content/uploads/2021/06/Jump-Squat.gif',
    youtube_url: 'https://youtube.com/shorts/U4s4mEQ5VOU',
    default_sets: 3, default_reps: '10-15',
    instructions: 'Squat then explode upward; land softly.',
    difficulty: 'intermediate',
  },
  {
    id: 'calf_raise',
    name: 'Calf Raise',
    muscle_groups: ['legs'],
    equipment: ['bodyweight'],
    gif_url: 'https://fitnessprogramer.com/wp-content/uploads/2021/02/Calf-Raise.gif',
    youtube_url: 'https://youtube.com/shorts/-M4-G8p1fCI',
    default_sets: 3, default_reps: '15-20',
    instructions: 'Rise onto toes; full range of motion.',
    difficulty: 'beginner',
  },

  // ── GLUTES ─────────────────────────────────────────────────────────────────
  {
    id: 'glute_bridge',
    name: 'Glute Bridge',
    muscle_groups: ['glutes', 'legs'],
    equipment: ['bodyweight'],
    gif_url: 'https://fitnessprogramer.com/wp-content/uploads/2021/02/Glute-Bridge.gif',
    youtube_url: 'https://youtube.com/shorts/OUgsJ8-Vi0E',
    default_sets: 3, default_reps: '15-20',
    instructions: 'Lie on back, feet flat; drive hips up, squeeze at top.',
    difficulty: 'beginner',
  },
  {
    id: 'hip_thrust_db',
    name: 'Dumbbell Hip Thrust',
    muscle_groups: ['glutes', 'legs'],
    equipment: ['dumbbells', 'bench'],
    gif_url: 'https://fitnessprogramer.com/wp-content/uploads/2021/06/Hip-Thrust.gif',
    youtube_url: 'https://youtube.com/shorts/SEdqd1n0cvg',
    default_sets: 4, default_reps: '10-15',
    instructions: 'Shoulders on bench, dumbbell on hips; thrust up.',
    difficulty: 'intermediate',
  },
  {
    id: 'donkey_kick',
    name: 'Donkey Kick',
    muscle_groups: ['glutes'],
    equipment: ['bodyweight'],
    gif_url: 'https://fitnessprogramer.com/wp-content/uploads/2021/02/Donkey-Kick.gif',
    youtube_url: 'https://youtube.com/shorts/SJ1Xuz9D-ZQ',
    default_sets: 3, default_reps: '15-20',
    instructions: 'On all fours; kick heel to ceiling, squeeze glute.',
    difficulty: 'beginner',
  },

  // ── CORE ───────────────────────────────────────────────────────────────────
  {
    id: 'plank',
    name: 'Plank',
    muscle_groups: ['core'],
    equipment: ['bodyweight'],
    gif_url: 'https://fitnessprogramer.com/wp-content/uploads/2021/02/Plank.gif',
    youtube_url: 'https://youtube.com/shorts/ASdvN_XEl_c',
    default_sets: 3, default_reps: '30-60s',
    instructions: 'Straight line from head to heels; breathe steadily.',
    difficulty: 'beginner',
  },
  {
    id: 'crunch',
    name: 'Crunch',
    muscle_groups: ['core'],
    equipment: ['bodyweight'],
    gif_url: 'https://fitnessprogramer.com/wp-content/uploads/2021/02/Crunch.gif',
    youtube_url: 'https://youtube.com/shorts/Xyd_fa5zoEU',
    default_sets: 3, default_reps: '15-20',
    instructions: 'Hands behind head; lift shoulder blades off floor.',
    difficulty: 'beginner',
  },
  {
    id: 'bicycle_crunch',
    name: 'Bicycle Crunch',
    muscle_groups: ['core'],
    equipment: ['bodyweight'],
    gif_url: 'https://fitnessprogramer.com/wp-content/uploads/2021/02/Bicycle-Crunch.gif',
    youtube_url: 'https://youtube.com/shorts/9FGilxCbdz8',
    default_sets: 3, default_reps: '20-25',
    instructions: 'Alternate elbow to opposite knee in cycling motion.',
    difficulty: 'beginner',
  },
  {
    id: 'leg_raise',
    name: 'Leg Raise',
    muscle_groups: ['core'],
    equipment: ['bodyweight'],
    gif_url: 'https://fitnessprogramer.com/wp-content/uploads/2021/02/Leg-Raise.gif',
    youtube_url: 'https://youtube.com/shorts/JB2oyawG9KI',
    default_sets: 3, default_reps: '12-15',
    instructions: 'Keep lower back flat; raise straight legs to 90°.',
    difficulty: 'intermediate',
  },
  {
    id: 'mountain_climber',
    name: 'Mountain Climber',
    muscle_groups: ['core', 'cardio'],
    equipment: ['bodyweight'],
    gif_url: 'https://fitnessprogramer.com/wp-content/uploads/2021/02/Mountain-Climber.gif',
    youtube_url: 'https://youtube.com/shorts/nmwgirgXLYM',
    default_sets: 3, default_reps: '20-30',
    instructions: 'In plank; drive knees to chest alternately at pace.',
    difficulty: 'intermediate',
  },
  {
    id: 'russian_twist',
    name: 'Russian Twist',
    muscle_groups: ['core'],
    equipment: ['bodyweight'],
    gif_url: 'https://fitnessprogramer.com/wp-content/uploads/2021/02/RUSSIAN-TWIST.gif',
    youtube_url: 'https://youtube.com/shorts/JyUqwkVpsi8',
    default_sets: 3, default_reps: '20-30',
    instructions: 'Lean back 45°; rotate torso side to side.',
    difficulty: 'intermediate',
  },
  {
    id: 'dead_bug',
    name: 'Dead Bug',
    muscle_groups: ['core'],
    equipment: ['bodyweight'],
    gif_url: 'https://fitnessprogramer.com/wp-content/uploads/2021/06/Dead-Bug.gif',
    youtube_url: 'https://youtube.com/shorts/4XLEnwUr1d8',
    default_sets: 3, default_reps: '10-12',
    instructions: 'Lower opposite arm and leg simultaneously; keep back flat.',
    difficulty: 'intermediate',
  },
]

export function getExerciseById(id: string): Exercise | undefined {
  return EXERCISES.find(e => e.id === id)
}

export function getExercisesByMuscle(muscle: string): Exercise[] {
  return EXERCISES.filter(e => e.muscle_groups.includes(muscle as any))
}

export function getExercisesByEquipment(equipment: string[]): Exercise[] {
  return EXERCISES.filter(e => e.equipment.some(eq => equipment.includes(eq)))
}
