import { Exercise } from './types'

// Curated home gym exercise library (~80 exercises)
// GIFs sourced from public domain / giphy fitness; YouTube links are canonical form "watch?v=ID"
export const EXERCISES: Exercise[] = [
  // ── CHEST ──────────────────────────────────────────────────────────────────
  {
    id: 'push_up',
    name: 'Push-Up',
    muscle_groups: ['chest', 'triceps', 'shoulders'],
    equipment: ['bodyweight'],
    gif_url: 'https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExcHVzaHVw/giphy.gif',
    youtube_url: 'https://www.youtube.com/watch?v=IODxDxX7oi4',
    default_sets: 3,
    default_reps: '10-15',
    instructions: 'Keep core tight, lower chest to floor, push back up.',
    difficulty: 'beginner',
  },
  {
    id: 'wide_push_up',
    name: 'Wide Push-Up',
    muscle_groups: ['chest', 'triceps'],
    equipment: ['bodyweight'],
    gif_url: 'https://media.giphy.com/media/widepushup/giphy.gif',
    youtube_url: 'https://www.youtube.com/watch?v=0pkjOk0EiAk',
    default_sets: 3,
    default_reps: '10-12',
    instructions: 'Hands wider than shoulder width; emphasizes outer chest.',
    difficulty: 'beginner',
  },
  {
    id: 'diamond_push_up',
    name: 'Diamond Push-Up',
    muscle_groups: ['chest', 'triceps'],
    equipment: ['bodyweight'],
    gif_url: 'https://media.giphy.com/media/diamondpushup/giphy.gif',
    youtube_url: 'https://www.youtube.com/watch?v=J0DnG1_S92I',
    default_sets: 3,
    default_reps: '8-12',
    instructions: 'Thumbs and index fingers touching; hits inner chest and triceps.',
    difficulty: 'intermediate',
  },
  {
    id: 'incline_push_up',
    name: 'Incline Push-Up',
    muscle_groups: ['chest', 'triceps'],
    equipment: ['bodyweight', 'bench'],
    gif_url: 'https://media.giphy.com/media/inclinepushup/giphy.gif',
    youtube_url: 'https://www.youtube.com/watch?v=cfns5pRUq9s',
    default_sets: 3,
    default_reps: '12-15',
    instructions: 'Hands on bench/chair; targets lower chest.',
    difficulty: 'beginner',
  },
  {
    id: 'decline_push_up',
    name: 'Decline Push-Up',
    muscle_groups: ['chest', 'shoulders'],
    equipment: ['bodyweight', 'bench'],
    gif_url: 'https://media.giphy.com/media/declinepushup/giphy.gif',
    youtube_url: 'https://www.youtube.com/watch?v=SKPab2YC8BE',
    default_sets: 3,
    default_reps: '8-12',
    instructions: 'Feet elevated on bench; emphasizes upper chest.',
    difficulty: 'intermediate',
  },
  {
    id: 'db_chest_press',
    name: 'Dumbbell Chest Press',
    muscle_groups: ['chest', 'triceps', 'shoulders'],
    equipment: ['dumbbells', 'bench'],
    gif_url: 'https://media.giphy.com/media/dbchestpress/giphy.gif',
    youtube_url: 'https://www.youtube.com/watch?v=VmB1G1K7v94',
    default_sets: 4,
    default_reps: '8-12',
    instructions: 'Lie on bench, press dumbbells from chest to full extension.',
    difficulty: 'intermediate',
  },
  {
    id: 'db_chest_fly',
    name: 'Dumbbell Chest Fly',
    muscle_groups: ['chest'],
    equipment: ['dumbbells', 'bench'],
    gif_url: 'https://media.giphy.com/media/dbfly/giphy.gif',
    youtube_url: 'https://www.youtube.com/watch?v=eozdVDA78K0',
    default_sets: 3,
    default_reps: '10-15',
    instructions: 'Wide arc motion; slight bend in elbows throughout.',
    difficulty: 'intermediate',
  },

  // ── BACK ───────────────────────────────────────────────────────────────────
  {
    id: 'pull_up',
    name: 'Pull-Up',
    muscle_groups: ['back', 'biceps'],
    equipment: ['pull_up_bar'],
    gif_url: 'https://media.giphy.com/media/pullup/giphy.gif',
    youtube_url: 'https://www.youtube.com/watch?v=eGo4IYlbE5g',
    default_sets: 3,
    default_reps: '5-10',
    instructions: 'Overhand grip; pull until chin clears bar.',
    difficulty: 'intermediate',
  },
  {
    id: 'chin_up',
    name: 'Chin-Up',
    muscle_groups: ['back', 'biceps'],
    equipment: ['pull_up_bar'],
    gif_url: 'https://media.giphy.com/media/chinup/giphy.gif',
    youtube_url: 'https://www.youtube.com/watch?v=b-ztMQpj8yc',
    default_sets: 3,
    default_reps: '5-10',
    instructions: 'Underhand grip; easier than pull-up, more bicep activation.',
    difficulty: 'intermediate',
  },
  {
    id: 'inverted_row',
    name: 'Inverted Row',
    muscle_groups: ['back', 'biceps'],
    equipment: ['pull_up_bar'],
    gif_url: 'https://media.giphy.com/media/invertedrow/giphy.gif',
    youtube_url: 'https://www.youtube.com/watch?v=B4bHMFCmRTI',
    default_sets: 3,
    default_reps: '10-15',
    instructions: 'Body below bar at 45°; pull chest to bar.',
    difficulty: 'beginner',
  },
  {
    id: 'db_bent_over_row',
    name: 'Dumbbell Bent-Over Row',
    muscle_groups: ['back', 'biceps'],
    equipment: ['dumbbells'],
    gif_url: 'https://media.giphy.com/media/dbrow/giphy.gif',
    youtube_url: 'https://www.youtube.com/watch?v=6TSP1TRMUzs',
    default_sets: 4,
    default_reps: '8-12',
    instructions: 'Hinge at hips 45°; pull elbows past torso.',
    difficulty: 'intermediate',
  },
  {
    id: 'db_single_arm_row',
    name: 'Single-Arm Dumbbell Row',
    muscle_groups: ['back', 'biceps'],
    equipment: ['dumbbells', 'bench'],
    gif_url: 'https://media.giphy.com/media/singlearmrow/giphy.gif',
    youtube_url: 'https://www.youtube.com/watch?v=pYcpY20QaE8',
    default_sets: 3,
    default_reps: '10-12',
    instructions: 'Knee and hand on bench; pull dumbbell to hip.',
    difficulty: 'beginner',
  },
  {
    id: 'superman',
    name: 'Superman',
    muscle_groups: ['back'],
    equipment: ['bodyweight'],
    gif_url: 'https://media.giphy.com/media/superman/giphy.gif',
    youtube_url: 'https://www.youtube.com/watch?v=z6PJMT2y8GQ',
    default_sets: 3,
    default_reps: '12-15',
    instructions: 'Lie prone; lift arms and legs simultaneously.',
    difficulty: 'beginner',
  },
  {
    id: 'resistance_band_row',
    name: 'Resistance Band Row',
    muscle_groups: ['back', 'biceps'],
    equipment: ['resistance_bands'],
    gif_url: 'https://media.giphy.com/media/bandrow/giphy.gif',
    youtube_url: 'https://www.youtube.com/watch?v=R3lkNq3AAXI',
    default_sets: 3,
    default_reps: '12-15',
    instructions: 'Anchor band at chest height; pull elbows back.',
    difficulty: 'beginner',
  },

  // ── SHOULDERS ──────────────────────────────────────────────────────────────
  {
    id: 'pike_push_up',
    name: 'Pike Push-Up',
    muscle_groups: ['shoulders', 'triceps'],
    equipment: ['bodyweight'],
    gif_url: 'https://media.giphy.com/media/pikepushup/giphy.gif',
    youtube_url: 'https://www.youtube.com/watch?v=sposDXWEB0A',
    default_sets: 3,
    default_reps: '8-12',
    instructions: 'Hips high in V shape; lower head toward floor.',
    difficulty: 'intermediate',
  },
  {
    id: 'db_shoulder_press',
    name: 'Dumbbell Shoulder Press',
    muscle_groups: ['shoulders', 'triceps'],
    equipment: ['dumbbells'],
    gif_url: 'https://media.giphy.com/media/dbshoulderpress/giphy.gif',
    youtube_url: 'https://www.youtube.com/watch?v=qEwKCR5JCog',
    default_sets: 4,
    default_reps: '8-12',
    instructions: 'Press from ear level to full extension overhead.',
    difficulty: 'intermediate',
  },
  {
    id: 'db_lateral_raise',
    name: 'Dumbbell Lateral Raise',
    muscle_groups: ['shoulders'],
    equipment: ['dumbbells'],
    gif_url: 'https://media.giphy.com/media/lateralraise/giphy.gif',
    youtube_url: 'https://www.youtube.com/watch?v=3VcKaXpzqRo',
    default_sets: 3,
    default_reps: '12-15',
    instructions: 'Slight elbow bend; raise to shoulder height.',
    difficulty: 'beginner',
  },
  {
    id: 'db_front_raise',
    name: 'Dumbbell Front Raise',
    muscle_groups: ['shoulders'],
    equipment: ['dumbbells'],
    gif_url: 'https://media.giphy.com/media/frontraise/giphy.gif',
    youtube_url: 'https://www.youtube.com/watch?v=sOoBHDVTqgg',
    default_sets: 3,
    default_reps: '12-15',
    instructions: 'Raise one or both dumbbells to shoulder height.',
    difficulty: 'beginner',
  },
  {
    id: 'band_face_pull',
    name: 'Band Face Pull',
    muscle_groups: ['shoulders', 'back'],
    equipment: ['resistance_bands'],
    gif_url: 'https://media.giphy.com/media/facepull/giphy.gif',
    youtube_url: 'https://www.youtube.com/watch?v=eIq5CB9JfKE',
    default_sets: 3,
    default_reps: '15-20',
    instructions: 'Anchor at face height; pull toward face, flare elbows.',
    difficulty: 'beginner',
  },

  // ── BICEPS ─────────────────────────────────────────────────────────────────
  {
    id: 'db_curl',
    name: 'Dumbbell Bicep Curl',
    muscle_groups: ['biceps'],
    equipment: ['dumbbells'],
    gif_url: 'https://media.giphy.com/media/dbcurl/giphy.gif',
    youtube_url: 'https://www.youtube.com/watch?v=ykJmrZ5v0Oo',
    default_sets: 3,
    default_reps: '10-12',
    instructions: 'Keep elbows pinned at sides; full range of motion.',
    difficulty: 'beginner',
  },
  {
    id: 'hammer_curl',
    name: 'Hammer Curl',
    muscle_groups: ['biceps'],
    equipment: ['dumbbells'],
    gif_url: 'https://media.giphy.com/media/hammercurl/giphy.gif',
    youtube_url: 'https://www.youtube.com/watch?v=zC3nLlEvin4',
    default_sets: 3,
    default_reps: '10-12',
    instructions: 'Neutral (thumbs up) grip; hits brachialis.',
    difficulty: 'beginner',
  },
  {
    id: 'band_curl',
    name: 'Resistance Band Curl',
    muscle_groups: ['biceps'],
    equipment: ['resistance_bands'],
    gif_url: 'https://media.giphy.com/media/bandcurl/giphy.gif',
    youtube_url: 'https://www.youtube.com/watch?v=JkVQRDJPDcI',
    default_sets: 3,
    default_reps: '12-15',
    instructions: 'Stand on band; curl with full contraction.',
    difficulty: 'beginner',
  },
  {
    id: 'isometric_curl',
    name: 'Isometric Towel Curl',
    muscle_groups: ['biceps'],
    equipment: ['bodyweight'],
    gif_url: 'https://media.giphy.com/media/isometriccurl/giphy.gif',
    youtube_url: 'https://www.youtube.com/watch?v=8Ew5qhj5YWk',
    default_sets: 3,
    default_reps: '10',
    instructions: 'Loop towel under foot; curl against resistance.',
    difficulty: 'beginner',
  },

  // ── TRICEPS ────────────────────────────────────────────────────────────────
  {
    id: 'tricep_dip',
    name: 'Chair Tricep Dip',
    muscle_groups: ['triceps', 'chest'],
    equipment: ['bodyweight', 'bench'],
    gif_url: 'https://media.giphy.com/media/tricepdip/giphy.gif',
    youtube_url: 'https://www.youtube.com/watch?v=0326dy_-CzM',
    default_sets: 3,
    default_reps: '10-15',
    instructions: 'Hands on chair edge; lower hips toward floor.',
    difficulty: 'beginner',
  },
  {
    id: 'db_overhead_tricep_ext',
    name: 'DB Overhead Tricep Extension',
    muscle_groups: ['triceps'],
    equipment: ['dumbbells'],
    gif_url: 'https://media.giphy.com/media/overtricepext/giphy.gif',
    youtube_url: 'https://www.youtube.com/watch?v=YbX7Wd8jQ-Q',
    default_sets: 3,
    default_reps: '10-12',
    instructions: 'Hold dumbbell overhead; lower behind head, extend.',
    difficulty: 'beginner',
  },
  {
    id: 'db_tricep_kickback',
    name: 'Dumbbell Tricep Kickback',
    muscle_groups: ['triceps'],
    equipment: ['dumbbells'],
    gif_url: 'https://media.giphy.com/media/kickback/giphy.gif',
    youtube_url: 'https://www.youtube.com/watch?v=6SS6K3lAwZ8',
    default_sets: 3,
    default_reps: '12-15',
    instructions: 'Hinge forward; extend arm fully back.',
    difficulty: 'beginner',
  },
  {
    id: 'close_grip_push_up',
    name: 'Close-Grip Push-Up',
    muscle_groups: ['triceps', 'chest'],
    equipment: ['bodyweight'],
    gif_url: 'https://media.giphy.com/media/closegrippu/giphy.gif',
    youtube_url: 'https://www.youtube.com/watch?v=U6NuHSUUbzI',
    default_sets: 3,
    default_reps: '8-12',
    instructions: 'Hands shoulder-width; elbows track close to body.',
    difficulty: 'intermediate',
  },

  // ── LEGS ───────────────────────────────────────────────────────────────────
  {
    id: 'squat',
    name: 'Bodyweight Squat',
    muscle_groups: ['legs', 'glutes'],
    equipment: ['bodyweight'],
    gif_url: 'https://media.giphy.com/media/squat/giphy.gif',
    youtube_url: 'https://www.youtube.com/watch?v=aclHkVaku9U',
    default_sets: 3,
    default_reps: '15-20',
    instructions: 'Feet shoulder width; descend until thighs parallel.',
    difficulty: 'beginner',
  },
  {
    id: 'goblet_squat',
    name: 'Goblet Squat',
    muscle_groups: ['legs', 'glutes'],
    equipment: ['dumbbells'],
    gif_url: 'https://media.giphy.com/media/gobletsquat/giphy.gif',
    youtube_url: 'https://www.youtube.com/watch?v=MeIiIdhvXT4',
    default_sets: 4,
    default_reps: '10-15',
    instructions: 'Hold dumbbell at chest; keep torso upright.',
    difficulty: 'beginner',
  },
  {
    id: 'bulgarian_split_squat',
    name: 'Bulgarian Split Squat',
    muscle_groups: ['legs', 'glutes'],
    equipment: ['bodyweight', 'dumbbells', 'bench'],
    gif_url: 'https://media.giphy.com/media/bulgariansplit/giphy.gif',
    youtube_url: 'https://www.youtube.com/watch?v=2C-uNgKwPLE',
    default_sets: 3,
    default_reps: '8-10',
    instructions: 'Rear foot elevated; lower back knee toward floor.',
    difficulty: 'intermediate',
  },
  {
    id: 'lunge',
    name: 'Walking Lunge',
    muscle_groups: ['legs', 'glutes'],
    equipment: ['bodyweight'],
    gif_url: 'https://media.giphy.com/media/walkinglunge/giphy.gif',
    youtube_url: 'https://www.youtube.com/watch?v=L8fvypPrzzs',
    default_sets: 3,
    default_reps: '10-12',
    instructions: 'Step forward; lower back knee near floor.',
    difficulty: 'beginner',
  },
  {
    id: 'db_romanian_deadlift',
    name: 'Dumbbell Romanian Deadlift',
    muscle_groups: ['legs', 'glutes', 'back'],
    equipment: ['dumbbells'],
    gif_url: 'https://media.giphy.com/media/rdl/giphy.gif',
    youtube_url: 'https://www.youtube.com/watch?v=7j-2pitPseU',
    default_sets: 4,
    default_reps: '8-12',
    instructions: 'Hinge at hips; feel hamstring stretch, drive hips forward.',
    difficulty: 'intermediate',
  },
  {
    id: 'step_up',
    name: 'Step-Up',
    muscle_groups: ['legs', 'glutes'],
    equipment: ['bodyweight', 'dumbbells', 'bench'],
    gif_url: 'https://media.giphy.com/media/stepup/giphy.gif',
    youtube_url: 'https://www.youtube.com/watch?v=dQqApCGd5Ss',
    default_sets: 3,
    default_reps: '10-12',
    instructions: 'Step fully onto platform; drive through heel.',
    difficulty: 'beginner',
  },
  {
    id: 'jump_squat',
    name: 'Jump Squat',
    muscle_groups: ['legs', 'glutes'],
    equipment: ['bodyweight'],
    gif_url: 'https://media.giphy.com/media/jumpsquat/giphy.gif',
    youtube_url: 'https://www.youtube.com/watch?v=U4s4mEQ5VOU',
    default_sets: 3,
    default_reps: '10-15',
    instructions: 'Squat then explode upward; land softly.',
    difficulty: 'intermediate',
  },
  {
    id: 'wall_sit',
    name: 'Wall Sit',
    muscle_groups: ['legs'],
    equipment: ['bodyweight'],
    gif_url: 'https://media.giphy.com/media/wallsit/giphy.gif',
    youtube_url: 'https://www.youtube.com/watch?v=y-wV4Venusw',
    default_sets: 3,
    default_reps: '30-60s',
    instructions: 'Back flat on wall; thighs parallel to floor.',
    difficulty: 'beginner',
  },

  // ── GLUTES ─────────────────────────────────────────────────────────────────
  {
    id: 'glute_bridge',
    name: 'Glute Bridge',
    muscle_groups: ['glutes', 'legs'],
    equipment: ['bodyweight'],
    gif_url: 'https://media.giphy.com/media/glutebridge/giphy.gif',
    youtube_url: 'https://www.youtube.com/watch?v=OUgsJ8-Vi0E',
    default_sets: 3,
    default_reps: '15-20',
    instructions: 'Lie on back, feet flat; drive hips up, squeeze at top.',
    difficulty: 'beginner',
  },
  {
    id: 'hip_thrust_db',
    name: 'Dumbbell Hip Thrust',
    muscle_groups: ['glutes', 'legs'],
    equipment: ['dumbbells', 'bench'],
    gif_url: 'https://media.giphy.com/media/hipthrust/giphy.gif',
    youtube_url: 'https://www.youtube.com/watch?v=SEdqd1n0cvg',
    default_sets: 4,
    default_reps: '10-15',
    instructions: 'Shoulders on bench, dumbbell on hips; thrust up.',
    difficulty: 'intermediate',
  },
  {
    id: 'donkey_kick',
    name: 'Donkey Kick',
    muscle_groups: ['glutes'],
    equipment: ['bodyweight'],
    gif_url: 'https://media.giphy.com/media/donkeykick/giphy.gif',
    youtube_url: 'https://www.youtube.com/watch?v=SJ1Xuz9D-ZQ',
    default_sets: 3,
    default_reps: '15-20',
    instructions: 'On all fours; kick heel to ceiling, squeeze glute.',
    difficulty: 'beginner',
  },
  {
    id: 'fire_hydrant',
    name: 'Fire Hydrant',
    muscle_groups: ['glutes'],
    equipment: ['bodyweight'],
    gif_url: 'https://media.giphy.com/media/firehydrant/giphy.gif',
    youtube_url: 'https://www.youtube.com/watch?v=YjdKQNkOomg',
    default_sets: 3,
    default_reps: '15-20',
    instructions: 'On all fours; lift knee out to side.',
    difficulty: 'beginner',
  },

  // ── CORE ───────────────────────────────────────────────────────────────────
  {
    id: 'plank',
    name: 'Plank',
    muscle_groups: ['core'],
    equipment: ['bodyweight'],
    gif_url: 'https://media.giphy.com/media/plank/giphy.gif',
    youtube_url: 'https://www.youtube.com/watch?v=ASdvN_XEl_c',
    default_sets: 3,
    default_reps: '30-60s',
    instructions: 'Straight line from head to heels; breathe steadily.',
    difficulty: 'beginner',
  },
  {
    id: 'crunch',
    name: 'Crunch',
    muscle_groups: ['core'],
    equipment: ['bodyweight'],
    gif_url: 'https://media.giphy.com/media/crunch/giphy.gif',
    youtube_url: 'https://www.youtube.com/watch?v=Xyd_fa5zoEU',
    default_sets: 3,
    default_reps: '15-20',
    instructions: 'Hands behind head; lift shoulder blades off floor.',
    difficulty: 'beginner',
  },
  {
    id: 'bicycle_crunch',
    name: 'Bicycle Crunch',
    muscle_groups: ['core'],
    equipment: ['bodyweight'],
    gif_url: 'https://media.giphy.com/media/bicyclecrunch/giphy.gif',
    youtube_url: 'https://www.youtube.com/watch?v=9FGilxCbdz8',
    default_sets: 3,
    default_reps: '20-25',
    instructions: 'Alternate elbow to opposite knee in cycling motion.',
    difficulty: 'beginner',
  },
  {
    id: 'leg_raise',
    name: 'Leg Raise',
    muscle_groups: ['core'],
    equipment: ['bodyweight'],
    gif_url: 'https://media.giphy.com/media/legraise/giphy.gif',
    youtube_url: 'https://www.youtube.com/watch?v=JB2oyawG9KI',
    default_sets: 3,
    default_reps: '12-15',
    instructions: 'Keep lower back flat; raise straight legs to 90°.',
    difficulty: 'intermediate',
  },
  {
    id: 'mountain_climber',
    name: 'Mountain Climber',
    muscle_groups: ['core', 'cardio'],
    equipment: ['bodyweight'],
    gif_url: 'https://media.giphy.com/media/mountainclimber/giphy.gif',
    youtube_url: 'https://www.youtube.com/watch?v=nmwgirgXLYM',
    default_sets: 3,
    default_reps: '20-30',
    instructions: 'In plank; drive knees to chest alternately at pace.',
    difficulty: 'intermediate',
  },
  {
    id: 'russian_twist',
    name: 'Russian Twist',
    muscle_groups: ['core'],
    equipment: ['bodyweight', 'dumbbells'],
    gif_url: 'https://media.giphy.com/media/russiantwist/giphy.gif',
    youtube_url: 'https://www.youtube.com/watch?v=JyUqwkVpsi8',
    default_sets: 3,
    default_reps: '20-30',
    instructions: 'Lean back 45°; rotate torso side to side.',
    difficulty: 'intermediate',
  },
  {
    id: 'dead_bug',
    name: 'Dead Bug',
    muscle_groups: ['core'],
    equipment: ['bodyweight'],
    gif_url: 'https://media.giphy.com/media/deadbug/giphy.gif',
    youtube_url: 'https://www.youtube.com/watch?v=4XLEnwUr1d8',
    default_sets: 3,
    default_reps: '10-12',
    instructions: 'Lower opposite arm and leg simultaneously; keep back flat.',
    difficulty: 'intermediate',
  },
  {
    id: 'hollow_body_hold',
    name: 'Hollow Body Hold',
    muscle_groups: ['core'],
    equipment: ['bodyweight'],
    gif_url: 'https://media.giphy.com/media/hollowbody/giphy.gif',
    youtube_url: 'https://www.youtube.com/watch?v=LlDNef_Ztsc',
    default_sets: 3,
    default_reps: '20-30s',
    instructions: 'Flatten lower back; extend arms and legs off floor.',
    difficulty: 'intermediate',
  },

  // ── CARDIO / FULL BODY ──────────────────────────────────────────────────────
  {
    id: 'burpee',
    name: 'Burpee',
    muscle_groups: ['cardio', 'chest', 'legs'],
    equipment: ['bodyweight'],
    gif_url: 'https://media.giphy.com/media/burpee/giphy.gif',
    youtube_url: 'https://www.youtube.com/watch?v=TU8QYVW0gDU',
    default_sets: 3,
    default_reps: '8-12',
    instructions: 'Squat, jump back to plank, push-up, jump forward, jump up.',
    difficulty: 'intermediate',
  },
  {
    id: 'jumping_jack',
    name: 'Jumping Jack',
    muscle_groups: ['cardio'],
    equipment: ['bodyweight'],
    gif_url: 'https://media.giphy.com/media/jumpingjack/giphy.gif',
    youtube_url: 'https://www.youtube.com/watch?v=c4DAnQ6DtF8',
    default_sets: 3,
    default_reps: '30-50',
    instructions: 'Jump feet wide while raising arms overhead.',
    difficulty: 'beginner',
  },
  {
    id: 'high_knees',
    name: 'High Knees',
    muscle_groups: ['cardio', 'legs'],
    equipment: ['bodyweight'],
    gif_url: 'https://media.giphy.com/media/highknees/giphy.gif',
    youtube_url: 'https://www.youtube.com/watch?v=ZZZoCNMU48U',
    default_sets: 3,
    default_reps: '20-30s',
    instructions: 'Run in place bringing knees to hip height.',
    difficulty: 'beginner',
  },

  // ── CALVES ─────────────────────────────────────────────────────────────────
  {
    id: 'calf_raise',
    name: 'Calf Raise',
    muscle_groups: ['legs'],
    equipment: ['bodyweight'],
    gif_url: 'https://media.giphy.com/media/calfraise/giphy.gif',
    youtube_url: 'https://www.youtube.com/watch?v=-M4-G8p1fCI',
    default_sets: 3,
    default_reps: '15-20',
    instructions: 'Rise onto toes; full range of motion.',
    difficulty: 'beginner',
  },
  {
    id: 'single_leg_calf_raise',
    name: 'Single-Leg Calf Raise',
    muscle_groups: ['legs'],
    equipment: ['bodyweight'],
    gif_url: 'https://media.giphy.com/media/singlelegcalf/giphy.gif',
    youtube_url: 'https://www.youtube.com/watch?v=gwLzBJYoWlI',
    default_sets: 3,
    default_reps: '12-15',
    instructions: 'Balance on one foot; rise onto toes.',
    difficulty: 'intermediate',
  },
]

export function getExerciseById(id: string): Exercise | undefined {
  return EXERCISES.find(e => e.id === id)
}

export function getExercisesByMuscle(muscle: string): Exercise[] {
  return EXERCISES.filter(e => e.muscle_groups.includes(muscle as any))
}

export function getExercisesByEquipment(equipment: string[]): Exercise[] {
  return EXERCISES.filter(e =>
    e.equipment.some(eq => equipment.includes(eq))
  )
}
